# permissions for end users to view globallokirules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: globallokirule-viewer-role
rules:
- apiGroups:
  - logging.opsgy.com
  resources:
  - globallokirules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - logging.opsgy.com
  resources:
  - globallokirules/status
  verbs:
  - get
