# permissions for end users to edit globallokirules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: globallokirule-editor-role
rules:
- apiGroups:
  - logging.opsgy.com
  resources:
  - globallokirules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logging.opsgy.com
  resources:
  - globallokirules/status
  verbs:
  - get
