# permissions for end users to view lokirules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lokirule-viewer-role
rules:
- apiGroups:
  - logging.opsgy.com
  resources:
  - lokirules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - logging.opsgy.com
  resources:
  - lokirules/status
  verbs:
  - get
