
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - logging.opsgy.com
  resources:
  - lokirules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logging.opsgy.com
  resources:
  - lokirules/finalizers
  verbs:
  - update
- apiGroups:
  - logging.opsgy.com
  resources:
  - lokirules/status
  verbs:
  - get
  - patch
  - update
