apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loki-rule-operator
  labels:
    app.kubernetes.io/name: loki-rule-operator
rules:
- apiGroups: ["logging.opsgy.com"]
  resources:
  - globallokirules
  - lokirules
  verbs: ["get", "list", "watch"]
- apiGroups: ["logging.opsgy.com"]
  resources:
  - globallokirules/status
  - lokirules/status
  verbs: ["patch"]