apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: loki-rule-operator
  labels:
    app.kubernetes.io/name: loki-rule-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: loki-rule-operator
subjects:
- kind: ServiceAccount
  name: loki-rule-operator
  namespace: kube-system
