
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: loki-rule-operator
  namespace: {{ $LOKI_RULES_CONFIGMAP_NAMESPACE }}
  labels:
    app.kubernetes.io/name: loki-rule-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: loki-rule-operator
subjects:
- kind: ServiceAccount
  name: loki-rule-operator
  namespace: kube-system
