
apiVersion: v1
kind: Service
metadata:
  name: loki-rule-operator
  namespace: kube-system
  labels:
    app.kubernetes.io/name: loki-rule-operator
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    targetPort: https
    protocol: TCP
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  selector:
    app.kubernetes.io/name: loki-rule-operator

